SRCS = any_oxm_match_field_test.cpp \
	   oxm_match_set_test.cpp \
	   any_action_test.cpp \
	   action_list_test.cpp \
	   action_set_test.cpp \
	   any_instruction_test.cpp \
	   instruction_set_test.cpp \
	   bucket_test.cpp \
	   any_queue_property_test.cpp \
	   packet_queue_test.cpp
TARGET_LIB = libcommon_type_test.dylib

-include ../../subdirectories.mk

