SRCS = output_test.cpp \
	   copy_ttl_out_test.cpp \
	   copy_ttl_in_test.cpp \
	   set_mpls_ttl_test.cpp \
	   decrement_mpls_ttl_test.cpp \
	   push_vlan_test.cpp \
	   pop_vlan_test.cpp \
	   push_mpls_test.cpp \
	   pop_mpls_test.cpp \
	   set_queue_test.cpp \
	   group_test.cpp \
	   set_nw_ttl_test.cpp \
	   decrement_nw_ttl_test.cpp \
	   set_field_test.cpp \
	   push_pbb_test.cpp \
	   pop_pbb_test.cpp
TARGET_LIB = libaction_test.dylib

-include ../../subdirectories.mk

