SRCS = description_test.cpp \
	   flow_stats_test.cpp \
	   aggregate_stats_test.cpp \
	   table_stats_test.cpp \
	   port_stats_test.cpp \
	   queue_stats_test.cpp \
	   port_description_test.cpp
TARGET_LIB = libmultipart_test.dylib

-include ../../subdirectories.mk

