VPATH = ../../../include/canard/network/openflow/v13/impl
SRCS = any_action.ipp \
	   any_instruction.ipp \
	   any_oxm_match_field.ipp \
	   any_queue_property.ipp \
	   any_hello_element.ipp \
	   any_table_feature_property.ipp \
	   action_list.ipp \
	   action_set.ipp \
	   instruction_set.ipp \
	   oxm_match_set.ipp

-include ../../libbulb.mk

