SRCS = match_field_test.cpp \
	   in_port_test.cpp \
	   in_phy_port_test.cpp \
	   eth_dst_test.cpp \
	   vlan_vid_test.cpp \
	   vlan_pcp_test.cpp \
	   ip_dscp_test.cpp \
	   ip_ecn_test.cpp \
	   ipv4_src_test.cpp \
	   ipv6_src_test.cpp \
	   ipv6_flabel_test.cpp \
	   mpls_label_test.cpp \
	   mpls_tc_test.cpp \
	   mpls_bos_test.cpp \
	   pbb_isid_test.cpp \
	   ipv6_exthdr_test.cpp
TARGET_LIB = liboxm_match_test.dylib

-include ../../subdirectories.mk

