SRCS = goto_table_test.cpp \
	   write_metadata_test.cpp \
	   write_actions_test.cpp \
	   apply_actions_test.cpp \
	   clear_actions_test.cpp \
	   meter_test.cpp
TARGET_LIB = libinstruction_test.dylib

-include ../subdirectories.mk

