SRCS = any_oxm_match_field_test.cpp \
	   any_action_test.cpp \
	   action_list_test.cpp \
	   action_set_test.cpp \
	   any_instruction_test.cpp \
	   instruction_set_test.cpp \
	   any_queue_property_test.cpp \
	   any_hello_element_test.cpp \
	   oxm_match_field_set_test.cpp \
	   any_meter_band_test.cpp \
	   meter_band_set_test.cpp
TARGET_LIB = libutility_test.dylib

-include ../../subdirectories.mk

