SRCS = description_test.cpp \
	   flow_stats_test.cpp \
	   aggregate_stats_test.cpp \
	   table_stats_test.cpp \
	   port_stats_test.cpp
TARGET_LIB = libstats_test.dylib

-include ../../subdirectories.mk

