SRCS = switch_features_test.cpp \
	   switch_config_test.cpp \
	   flow_add_test.cpp \
	   flow_modify_test.cpp \
	   flow_delete_test.cpp \
	   port_mod_test.cpp \
	   queue_config_test.cpp \
	   packet_out_test.cpp \
	   barrier_test.cpp \
	   packet_in_test.cpp \
	   flow_removed_test.cpp
TARGET_LIB = libmessage_test.dylib

-include ../../subdirectories.mk

